// Code generated by protoc-gen-go. DO NOT EDIT.
// source: requester.proto

/*
Package requester is a generated protocol buffer package.

It is generated from these files:
	requester.proto

It has these top-level messages:
	Request
	Response
*/
package requester

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Request struct {
	KeyId string `protobuf:"bytes,1,opt,name=key_id,json=keyId" json:"key_id,omitempty"`
}

func (m *Request) Reset()                    { *m = Request{} }
func (m *Request) String() string            { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()               {}
func (*Request) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Request) GetKeyId() string {
	if m != nil {
		return m.KeyId
	}
	return ""
}

type Response struct {
	Keyvalue map[string]string `protobuf:"bytes,2,rep,name=keyvalue" json:"keyvalue,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Response) GetKeyvalue() map[string]string {
	if m != nil {
		return m.Keyvalue
	}
	return nil
}

func init() {
	proto.RegisterType((*Request)(nil), "requester.Request")
	proto.RegisterType((*Response)(nil), "requester.Response")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Requester service

type RequesterClient interface {
	Process(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type requesterClient struct {
	cc *grpc.ClientConn
}

func NewRequesterClient(cc *grpc.ClientConn) RequesterClient {
	return &requesterClient{cc}
}

func (c *requesterClient) Process(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/requester.Requester/Process", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Requester service

type RequesterServer interface {
	Process(context.Context, *Request) (*Response, error)
}

func RegisterRequesterServer(s *grpc.Server, srv RequesterServer) {
	s.RegisterService(&_Requester_serviceDesc, srv)
}

func _Requester_Process_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RequesterServer).Process(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/requester.Requester/Process",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RequesterServer).Process(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _Requester_serviceDesc = grpc.ServiceDesc{
	ServiceName: "requester.Requester",
	HandlerType: (*RequesterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Process",
			Handler:    _Requester_Process_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "requester.proto",
}

func init() { proto.RegisterFile("requester.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 244 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2f, 0x4a, 0x2d, 0x2c,
	0x4d, 0x2d, 0x2e, 0x49, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x84, 0x0b, 0x48,
	0xc9, 0xa4, 0xe7, 0xe7, 0xa7, 0xe7, 0xa4, 0xea, 0x27, 0x16, 0x64, 0xea, 0x27, 0xe6, 0xe5, 0xe5,
	0x97, 0x24, 0x96, 0x64, 0xe6, 0xe7, 0x15, 0x43, 0x14, 0x2a, 0x29, 0x70, 0xb1, 0x07, 0x41, 0x94,
	0x0a, 0x89, 0x72, 0xb1, 0x65, 0xa7, 0x56, 0xc6, 0x67, 0xa6, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0x70,
	0x06, 0xb1, 0x66, 0xa7, 0x56, 0x7a, 0xa6, 0x28, 0xb5, 0x31, 0x72, 0x71, 0x04, 0xa5, 0x16, 0x17,
	0xe4, 0xe7, 0x15, 0xa7, 0x0a, 0xd9, 0x72, 0x71, 0x64, 0xa7, 0x56, 0x96, 0x25, 0xe6, 0x94, 0xa6,
	0x4a, 0x30, 0x29, 0x30, 0x6b, 0x70, 0x1b, 0x29, 0xea, 0x21, 0xec, 0x86, 0x29, 0xd3, 0xf3, 0x86,
	0xaa, 0x71, 0xcd, 0x2b, 0x29, 0xaa, 0x0c, 0x82, 0x6b, 0x91, 0xb2, 0xe6, 0xe2, 0x45, 0x91, 0x12,
	0x12, 0xe0, 0x62, 0xce, 0x4e, 0xad, 0x84, 0x5a, 0x08, 0x62, 0x0a, 0x89, 0x70, 0xb1, 0xc2, 0x8c,
	0x07, 0x3b, 0x02, 0xcc, 0xb1, 0x62, 0xb2, 0x60, 0x34, 0x8a, 0xe3, 0xe2, 0x0c, 0x82, 0x59, 0x25,
	0x14, 0xc8, 0xc5, 0x1e, 0x50, 0x94, 0x9f, 0x9c, 0x5a, 0x5c, 0x2c, 0x24, 0x84, 0xe2, 0x02, 0x30,
	0x4b, 0x4a, 0x18, 0x8b, 0xab, 0x94, 0x64, 0x9b, 0x2e, 0x3f, 0x99, 0xcc, 0x24, 0x2e, 0x24, 0xaa,
	0x5f, 0x66, 0xa0, 0x9f, 0x5a, 0x92, 0x9c, 0xa2, 0x9f, 0x9d, 0x5a, 0xa9, 0x5f, 0x0d, 0xf1, 0x74,
	0x6d, 0x12, 0x1b, 0x38, 0x44, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x4e, 0xf1, 0x5d, 0x49,
	0x4d, 0x01, 0x00, 0x00,
}
